import Head from "next/head";
import { type ReactNode } from "react";

interface PageLayoutProps {
  children: ReactNode;
  pageTitle: string;
}

const PageLayout = ({ children, pageTitle }: PageLayoutProps) => {

    const navbar = (
        <div className="flex flex-col items-center justify-center gap-4">
            <h1>
            </h1>
        </div>
    )

   return (
        <>
            <Head>
                <title>{ pageTitle }</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gray-950">
                { navbar }
                <div>
                    <h1 className="text-5xl font-mono font-extrabold tracking-tight text-green-600 sm:text-[5rem]">
                    </h1>
                    <div>{ children }</div>
                </div>
            </main>
        </>
    )
}

export default PageLayout;
