import Head from "next/head";
import { type ReactNode } from "react";
import { useState } from "react";

interface PageLayoutProps {
  children: ReactNode;
  pageTitle: string;
}

const PageLayout = ({ children, pageTitle }: PageLayoutProps) => {

    const navbar = (
        <div className="hidden sm:flex flex items-center justify-in-between gap-4 text-white absolute pl-10">
            <h1 className="text-xl font-mono text-white-100">home</h1>
            <h1 className="text-xl font-mono text-white-100">about</h1>
            <h1 className="text-xl font-mono text-white-100">meetings</h1>
            <h1 className="text-xl font-mono text-white-100">contact</h1>
        </div>
    )

    const mobileSidebar = (
        <div className="sm:hidden flex items-center justify-in-between gap-4 text-white absolute pl-10">
            <h1 className="text-xl font-mono text-white-100">home</h1>
            <h1 className="text-xl font-mono text-white-100">about</h1>
            <h1 className="text-xl font-mono text-white-100">meetings</h1>
            <h1 className="text-xl font-mono text-white-100">contact</h1>
        </div>
    )

    const [mobileNavbarToggle, setMobileNavbarToggle] = useState<boolean>(false);

    const handleClick = () =>
    {
      setMobileNavbarToggle(!mobileNavbarToggle);
    }

   return (
        <>
            <Head>
                <title>{ pageTitle }</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-gray-950">
                <div className="cursor-pointer sm:hidden" onClick={handleClick}>
                    <h1 className="text-xl font-mono text-white-100">hi</h1>
                </div>
                { mobileNavbarToggle ? mobileSidebar : null }
                { navbar }
                <div className="flex min-h-screen flex-col items-center justify-center">
                    <h1 className="text-5xl font-mono font-extrabold tracking-tight text-green-600 sm:text-[5rem]">
                    </h1>
                    <div>{ children }</div>
                </div>
            </main>
        </>
    )
}

export default PageLayout;
